// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4PP1kBogxYwUU2ui5Pk-D9i1syOISz_o',
    appId: '1:251409487085:web:ea77c44d219ea28ae2e8e4',
    messagingSenderId: '251409487085',
    projectId: 'hodotrek',
    authDomain: 'hodotrek.firebaseapp.com',
    storageBucket: 'hodotrek.firebasestorage.app',
    measurementId: 'G-DV4WKRG5KN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvtVRV-tMkMHRxMTZ0mQ9RnDLnLW5QKDg',
    appId: '1:251409487085:android:2448805881bd4324e2e8e4',
    messagingSenderId: '251409487085',
    projectId: 'hodotrek',
    storageBucket: 'hodotrek.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAckafRO3FndXXTj4DF2-sNdNJnOaDWFWI',
    appId: '1:251409487085:ios:b132448269a73698e2e8e4',
    messagingSenderId: '251409487085',
    projectId: 'hodotrek',
    storageBucket: 'hodotrek.firebasestorage.app',
    iosClientId: '251409487085-ej09bjdfsncj1kpck9pltobpjs052t1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.parser',
  );
}
